# Generated by Django 5.0.4 on 2024-06-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=200, null=True)),
                ("ifsc_code", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "user_account_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("BUSINESS", "Business"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                    ),
                ),
                (
                    "bank_account_type",
                    models.CharField(
                        choices=[("SAVINGS", "Savings"), ("CURRENT", "Current")],
                        default="SAVINGS",
                        max_length=20,
                    ),
                ),
                ("pan_no", models.CharField(blank=True, max_length=200, null=True)),
                ("gstin_no", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=200, null=True)),
                ("ifsc_code", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bank_account_type",
                    models.CharField(
                        choices=[("SAVINGS", "Savings"), ("CURRENT", "Current")],
                        default="SAVINGS",
                        max_length=20,
                    ),
                ),
                ("pan_no", models.CharField(blank=True, max_length=200, null=True)),
                ("gstin_no", models.CharField(blank=True, max_length=200, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.customuser",
                    ),
                ),
            ],
        ),
    ]
