# Generated by Django 5.0.4 on 2024-06-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_holder_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("card_no", models.CharField(blank=True, max_length=16, null=True)),
                ("expiry_date", models.CharField(blank=True, max_length=5, null=True)),
                ("cvv_no", models.CharField(blank=True, max_length=3, null=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.customuser",
                    ),
                ),
            ],
        ),
    ]
