# Generated by Django 5.0.4 on 2024-06-17 11:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                ("nick_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("pan_no", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "adhaar_no",
                    models.CharField(
                        blank=True, default=None, max_length=12, null=True
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("BUSINESS", "Business"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "company_pan_no",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "company_adhaar_no",
                    models.CharField(
                        blank=True, default=None, max_length=12, null=True
                    ),
                ),
                ("otp", models.IntegerField(blank=True, null=True)),
                ("is_social_login", models.BooleanField(default=False)),
                (
                    "custom_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kyc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=200)),
                ("document_name", models.CharField(max_length=200)),
                ("document_id", models.CharField(max_length=200)),
                (
                    "document_image",
                    models.ImageField(
                        default=None, null=True, upload_to="kyc-image/document/%y/%m/%d"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.customuser",
                    ),
                ),
            ],
        ),
    ]
